// AUTO-GENERATED by scripts/gen-concept-vocab.ts — do not edit by hand.
// Source: reference/concept-mining/胚胎學.concepts.json + reference/blueprint-coarse.json
import type { SubjectConceptTree } from './types'

export const embryologyTree: SubjectConceptTree = {
  subjectId: "胚胎學",
  paper: "醫學一",
  chapters: [
  { id: "embryology-development", zh: "胚胎及發育生物學（受精、胚層、器官形成與發育）", en: "formation of embryo and fetus, development of organs" },
  ],
  leaves: [
  { id: "gametogenesis-fertilization", zh: "配子形成與受精", en: "Gametogenesis and Fertilization", chapterId: "embryology-development", synonyms: ["受精","配子發生","睪丸決定因子","SRY","quickening","胎動","排卵週期荷爾蒙變化","透明層 hatching","zona pellucida","染色體數目異常","trisomy"] },
  { id: "early-cleavage-implantation", zh: "早期卵裂與著床", en: "Early Cleavage and Implantation", chapterId: "embryology-development", synonyms: ["囊胚","blastocyst","內細胞團","inner cell mass","滋養層","trophoblast","絨毛膜絨毛","chorionic villus","hCG","human chorionic gonadotrophin","著床","羊膜腔","卵黃囊"] },
  { id: "germ-layers-gastrulation", zh: "三胚層形成與原腸胚形成", en: "Germ Layers and Gastrulation", chapterId: "embryology-development", synonyms: ["原條","primitive streak","脊索","notochord","外胚層衍生物","ectoderm derivatives","中胚層衍生物","mesoderm derivatives","神經嵴","neural crest","軸旁中胚層","paraxial mesoderm","體節","somite","骶尾畸胎瘤","sacrococcygeal teratoma","胚內體腔","intraembryonic coelom"] },
  { id: "neural-tube-development", zh: "神經管與中樞神經系統發育", en: "Neural Tube and Central Nervous System Development", chapterId: "embryology-development", synonyms: ["神經孔閉合","neuropore closure","腦泡","brain vesicle","prosencephalon","rhombencephalon","基板","basal plate","翼板","alar plate","視神經","optic nerve","神經垂體","neurohypophysis","大腦導水管","cerebral aqueduct"] },
  { id: "pharyngeal-arches", zh: "咽弓、咽囊與咽溝發育（含耳、顏面）", en: "Pharyngeal Arches, Pouches, and Grooves (Branchial Apparatus)", chapterId: "embryology-development", synonyms: ["咽弓","pharyngeal arch","branchial arch","咽囊","pharyngeal pouch","咽溝","pharyngeal groove","頸竇","cervical sinus","鰓竇","branchial sinus","聽小骨","auditory ossicle","鼓膜","tympanic membrane","甲狀腺發育","thyroid development","唇顎裂","cleft lip and palate","舌發育","tongue development","咽膜","pharyngeal membrane"] },
  { id: "cardiovascular-development", zh: "心臟血管系統發育", en: "Cardiovascular System Development", chapterId: "embryology-development", synonyms: ["心房間隔","interatrial septum","第一中隔","septum primum","第二中隔","septum secundum","卵圓孔","foramen ovale","動脈導管","ductus arteriosus","動脈韌帶","ligamentum arteriosum","胎兒循環","fetal circulation","臍靜脈","umbilical vein","蒲金氏纖維","Purkinje fiber","胸心包膜","pleuropericardial membrane","主動脈弓","aortic arch"] },
  { id: "GI-development", zh: "消化系統發育", en: "Gastrointestinal System Development", chapterId: "embryology-development", synonyms: ["前腸","foregut","中腸環","midgut loop","中腸旋轉","midgut rotation","十二指腸發育","duodenum development","胰臟發育","pancreas development","脾臟發育","spleen development","肛管","anal canal","肝臟發育","liver development","腸繫膜","mesentery"] },
  { id: "urogenital-development", zh: "泌尿生殖系統發育", en: "Urogenital System Development", chapterId: "embryology-development", synonyms: ["中腎管","mesonephric duct","Wolffian duct","副中腎管","paramesonephric duct","Müllerian duct","後腎憩室","metanephric diverticulum","輸尿管芽","ureteric bud","性腺分化","gonad differentiation","假陰陽人","pseudohermaphroditism","穆勒氏抑制物","Müllerian inhibiting substance","膀胱發育","urinary bladder development","陰道發育","vagina development","精索積水","hydrocele"] },
  { id: "limb-axial-musculoskeletal-development", zh: "四肢與中軸骨骼肌肉系統發育", en: "Limb and Axial Musculoskeletal Development", chapterId: "embryology-development", synonyms: ["生骨節","sclerotome","肌節","myotome","軸下肌","hypaxial muscle","肢芽","limb bud","頂外胚層嵴","apical ectodermal ridge","顱骨發育","cranium development","顱縫","cranial suture","舟形頭","scaphocephaly"] },
  { id: "respiratory-development", zh: "呼吸系統發育", en: "Respiratory System Development", chapterId: "embryology-development", synonyms: ["呼吸原基","respiratory primordium","氣管食道瘻管","tracheoesophageal fistula","肺發育分期","lung development stages","偽腺期","pseudoglandular stage","小管期","canalicular stage","末囊期","terminal sac stage","肺泡期","alveolar stage","血氣障壁","blood-air barrier","表面張力劑","surfactant"] },
  { id: "body-wall-diaphragm-development", zh: "體壁與橫膈發育", en: "Body Wall and Diaphragm Development", chapterId: "embryology-development", synonyms: ["橫膈","diaphragm","橫中隔","septum transversum","胸腹膜","pleuroperitoneal membrane","先天性橫膈疝","congenital diaphragmatic hernia","臍疝","umbilical herniation","腹膜皺襞","peritoneal fold"] },
  { id: "special-sense-integument-development", zh: "特殊感覺器官與皮膚附屬器發育（眼、皮膚）", en: "Special Sense Organ and Integument Development (Eye, Skin Appendages)", chapterId: "embryology-development", synonyms: ["眼發育","eye development","視杯","optic cup","角膜","cornea","視網膜色素上皮","retinal pigment epithelium","汗腺","sweat gland","皮脂腺","sebaceous gland","體表外胚層","surface ectoderm"], bottomUp: true },
  ],
}
