// AUTO-GENERATED by scripts/gen-concept-vocab.ts — do not edit by hand.
// Source: reference/concept-mining/組織學.concepts.json + reference/blueprint-coarse.json
import type { SubjectConceptTree } from './types'

export const histologyTree: SubjectConceptTree = {
  subjectId: "組織學",
  paper: "醫學一",
  chapters: [
  { id: "cells-tissues-organs", zh: "細胞、基本組織及器官", en: "cells, fundamental tissues and organs" },
  ],
  leaves: [
  { id: "nervous-tissue-neuron-and-glia", zh: "神經組織：神經元與神經膠細胞", en: "Nervous Tissue: Neurons and Neuroglia", chapterId: "cells-tissues-organs", synonyms: ["neuroglia","Schwann cell","satellite cell","blood-brain barrier","axonal transport","神經膠細胞","許旺細胞","衛星細胞","血腦屏障","軸突運輸"] },
  { id: "endocrine-system-histology", zh: "內分泌系統組織學", en: "Endocrine System Histology", chapterId: "cells-tissues-organs", synonyms: ["thyroid follicle","adrenal cortex","adrenal medulla","pituitary gland","Leydig cell","甲狀腺濾泡","腎上腺皮質","腦下垂體","萊氏細胞"] },
  { id: "male-reproductive-system-histology", zh: "男性生殖系統組織學", en: "Male Reproductive System Histology", chapterId: "cells-tissues-organs", synonyms: ["seminiferous tubule","Sertoli cell","epididymis","prostate","spermiogenesis","細精管","睪丸支持細胞","精子成型","副睪","前列腺"] },
  { id: "muscle-tissue-comparative-histology", zh: "肌肉組織比較組織學", en: "Comparative Histology of Muscle Tissue", chapterId: "cells-tissues-organs", synonyms: ["skeletal muscle","smooth muscle","cardiac muscle","sarcolemma","motor end plate","muscle spindle","intercalated disc","骨骼肌","平滑肌","心肌","運動終板","肌梭","心肌間盤"] },
  { id: "digestive-system-small-and-large-intestine", zh: "消化系統：小腸與大腸組織學", en: "Digestive System: Small and Large Intestine Histology", chapterId: "cells-tissues-organs", synonyms: ["crypts of Lieberkühn","Brunner's gland","teniae coli","appendix","duodenum","jejunum","ileum","colon","腸腺","十二指腸腺","結腸帶","闌尾"] },
  { id: "cell-biology-organelles-and-cytoskeleton", zh: "細胞胞器與細胞骨架", en: "Cell Organelles and Cytoskeleton", chapterId: "cells-tissues-organs", synonyms: ["organelle","細胞骨架","microtubule","mitochondria","細胞生物學"] },
  { id: "epithelial-tissue-classification-and-lining", zh: "上皮組織分類與器官內襯", en: "Epithelial Tissue Classification and Lining Epithelium", chapterId: "cells-tissues-organs", synonyms: ["simple squamous epithelium","stratified squamous epithelium","transitional epithelium","urothelium","pseudostratified columnar epithelium","移形上皮","泌尿上皮","偽複層柱狀上皮"] },
  { id: "bone-histology-and-ossification", zh: "骨組織學與骨化作用", en: "Bone Histology and Ossification", chapterId: "cells-tissues-organs", synonyms: ["osteoblast","osteocyte","osteoclast","intramembranous ossification","endochondral ossification","膜內骨化","軟骨內骨化","骨母細胞","蝕骨細胞"] },
  { id: "cartilage-histology", zh: "軟骨組織學", en: "Cartilage Histology", chapterId: "cells-tissues-organs", synonyms: ["hyaline cartilage","elastic cartilage","fibrocartilage","透明軟骨","彈性軟骨","纖維軟骨","interstitial growth","appositional growth"] },
  { id: "vascular-histology-arteries-veins-capillaries", zh: "血管組織學（動脈、靜脈、微血管）", en: "Vascular Histology (Arteries, Veins, Capillaries)", chapterId: "cells-tissues-organs", synonyms: ["elastic artery","muscular artery","fenestrated capillary","continuous capillary","pericyte","彈性動脈","肌型動脈","穿孔型微血管","周細胞"] },
  { id: "lymphoid-organs-histology", zh: "淋巴器官組織學", en: "Lymphoid Organ Histology", chapterId: "cells-tissues-organs", synonyms: ["lymph node","spleen","Peyer's patch","plasma cell","淋巴結","脾臟","培亞氏斑","漿細胞"] },
  { id: "integumentary-system-skin-histology", zh: "皮膚組織學", en: "Integumentary System (Skin) Histology", chapterId: "cells-tissues-organs", synonyms: ["epidermis","hair follicle","Merkel cell","Langerhans cell","表皮","毛囊","蘭氏細胞"] },
  { id: "digestive-system-esophagus-and-stomach", zh: "消化系統：食道與胃組織學", en: "Digestive System: Esophagus and Stomach Histology", chapterId: "cells-tissues-organs", synonyms: ["parietal cell","chief cell","gastric gland","pyloric gland","fundic gland","胃腺壁細胞","胃底腺","胃幽門腺","主細胞"] },
  { id: "respiratory-system-histology", zh: "呼吸系統組織學", en: "Respiratory System Histology", chapterId: "cells-tissues-organs", synonyms: ["trachea","bronchus","bronchiole","type-I pneumocyte","type-II pneumocyte","olfactory epithelium","氣管","支氣管","肺泡細胞","嗅覺上皮"] },
  { id: "female-reproductive-system-histology", zh: "女性生殖系統組織學", en: "Female Reproductive System Histology", chapterId: "cells-tissues-organs", synonyms: ["corpus luteum","ovarian follicle","endometrium","chorionic villi","zona pellucida","黃體","卵巢濾泡","子宮內膜","絨毛膜絨毛","透明帶"] },
  { id: "epithelial-surface-specializations-and-junctions", zh: "上皮細胞表面特化構造與細胞接合", en: "Epithelial Surface Specializations and Cell Junctions", chapterId: "cells-tissues-organs", synonyms: ["microvilli","stereocilia","desmosome","hemidesmosome","tight junction","gap junction","細胞接合","半橋粒","靜纖毛"] },
  { id: "digestive-system-liver-gallbladder-and-pancreas", zh: "消化系統：肝、膽囊與胰臟外分泌組織學", en: "Digestive System: Liver, Gallbladder, and Exocrine Pancreas Histology", chapterId: "cells-tissues-organs", synonyms: ["Rokitansky-Aschoff sinus","bile duct","hepatocyte","acinar cell","肝小葉","駱阿氏竇","膽管","肝細胞"] },
  { id: "urinary-system-histology", zh: "泌尿系統組織學", en: "Urinary System Histology", chapterId: "cells-tissues-organs", synonyms: ["nephron","proximal convoluted tubule","distal convoluted tubule","juxtaglomerular apparatus","brush border","近曲小管","遠曲小管","近腎絲球器","刷狀緣"] },
  { id: "glandular-epithelium-and-secretion-mechanisms", zh: "腺體上皮與分泌機轉", en: "Glandular Epithelium and Modes of Secretion", chapterId: "cells-tissues-organs", synonyms: ["merocrine","apocrine","holocrine","myoepithelial cell","部分分泌","頂漿分泌","全漿分泌","肌上皮細胞"] },
  { id: "connective-tissue-proper-fibers-and-fibroblasts", zh: "結締組織本體、纖維與纖維母細胞", en: "Connective Tissue Proper, Fibers, and Fibroblasts", chapterId: "cells-tissues-organs", synonyms: ["collagen fiber","elastic fiber","adipose tissue","fibroblast","膠原纖維","彈性纖維","脂肪組織"] },
  { id: "blood-cells-and-hematopoiesis", zh: "血液細胞與造血", en: "Blood Cells and Hematopoiesis", chapterId: "cells-tissues-organs", synonyms: ["platelet","leukocyte","erythropoiesis","bone marrow","血小板","白血球","紅血球生成","骨髓"] },
  { id: "digestive-system-salivary-glands", zh: "消化系統：唾液腺組織學", en: "Digestive System: Salivary Gland Histology", chapterId: "cells-tissues-organs", synonyms: ["parotid gland","serous demilune","mucous acinus","耳下腺","漿液半月","黏液腺泡"] },
  { id: "special-senses-eye-and-ear-histology", zh: "特殊感覺器官組織學（眼與耳）", en: "Special Senses: Eye and Ear Histology", chapterId: "cells-tissues-organs", synonyms: ["cornea","iris","ciliary body","membranous labyrinth","角膜","虹膜","睫狀體","膜性迷路"] },
  { id: "digestive-system-oral-cavity-tongue-and-teeth", zh: "消化系統：口腔、舌與牙齒組織學", en: "Digestive System: Oral Cavity, Tongue, and Teeth Histology", chapterId: "cells-tissues-organs", synonyms: ["circumvallate papillae","taste bud","cementum","dentin","enamel","輪廓乳突","齒堊質","牙本質","琺瑯質"] },
  { id: "microscopy-and-tissue-preparation-techniques", zh: "顯微技術與組織處理", en: "Microscopy and Tissue Preparation Techniques", chapterId: "cells-tissues-organs", synonyms: ["freeze fracture","formalin fixation","bright-field microscope","冷凍割斷術","福馬林固定"] },
  ],
}
