// AUTO-GENERATED by scripts/gen-concept-vocab.ts — do not edit by hand.
import type { ConceptVocab } from './types'
import { biochemistryTree } from './biochemistry'
import { anatomyTree } from './anatomy'
import { embryologyTree } from './embryology'
import { histologyTree } from './histology'
import { physiologyTree } from './physiology'
import { microbiologyTree } from './microbiology'
import { immunologyTree } from './immunology'
import { parasitologyTree } from './parasitology'
import { pharmacologyTree } from './pharmacology'
import { pathologyTree } from './pathology'
import { publicHealthTree } from './public-health'

export const CONCEPT_VOCAB: ConceptVocab = {
  "生物化學": biochemistryTree,
  "解剖學": anatomyTree,
  "胚胎學": embryologyTree,
  "組織學": histologyTree,
  "生理學": physiologyTree,
  "微生物學": microbiologyTree,
  "免疫學": immunologyTree,
  "寄生蟲學": parasitologyTree,
  "藥理學": pharmacologyTree,
  "病理學": pathologyTree,
  "公共衛生學": publicHealthTree,
}

export * from './types'
export { validateConceptVocab, resolveLeaf, normalizeSurface, type ConceptVocabFailure } from './validator'

/** All leaves across all subjects, tagged with their subjectId. */
export const ALL_LEAVES = Object.values(CONCEPT_VOCAB).flatMap((t) =>
  t.leaves.map((l) => ({ ...l, subjectId: t.subjectId })),
)
