// AUTO-GENERATED by scripts/gen-concept-vocab.ts — do not edit by hand.
// Source: reference/concept-mining/寄生蟲學.concepts.json + reference/blueprint-coarse.json
import type { SubjectConceptTree } from './types'

export const parasitologyTree: SubjectConceptTree = {
  subjectId: "寄生蟲學",
  paper: "醫學二",
  chapters: [
  { id: "nematodes", zh: "線蟲", en: "nematodes" },
  { id: "trematodes", zh: "吸蟲", en: "trematodes" },
  { id: "cestodes", zh: "絛蟲", en: "cestodes" },
  { id: "protozoa", zh: "原蟲", en: "protozoa" },
  { id: "arthropod-vectors", zh: "病媒節肢動物", en: "arthropods as vectors" },
  ],
  leaves: [
  { id: "foodborne-tissue-nematodes", zh: "食因性組織線蟲（旋毛蟲／菲律賓毛線蟲／海獸胃線蟲／棘顎口線蟲／麥地那線蟲／肝毛線蟲）", en: "foodborne and tissue-invasive nematodes (Trichinella spiralis, Capillaria philippinensis, Anisakis spp., Gnathostoma spinigerum, Dracunculus medinensis)", chapterId: "nematodes", synonyms: ["旋毛蟲症 trichinellosis","腸道毛細線蟲症","海獸胃線蟲症 anisakiasis","棘顎口線蟲症 gnathostomiasis","麥地那龍線蟲症 dracunculiasis","低蛋白血症 hypoproteinemia","肝毛線蟲假性感染 spurious infection"] },
  { id: "intestinal-nematodes-soil-transmitted", zh: "腸道土壤傳播線蟲（蛔蟲／蟯蟲／鞭蟲／鉤蟲／糞小桿線蟲）", en: "soil-transmitted intestinal nematodes (Ascaris, Enterobius, Trichuris, hookworm, Strongyloides)", chapterId: "nematodes", synonyms: ["蛔蟲症","蟯蟲症","鞭蟲症","鉤蟲病","糞小桿線蟲症","strongyloidiasis","autoinfection","notched tail filariform larva","iron deficiency anemia"] },
  { id: "lymphatic-and-subcutaneous-filariasis", zh: "淋巴絲蟲病與皮下絲蟲病（班氏絲蟲／馬來絲蟲／羅阿絲蟲／蟠尾絲蟲）", en: "lymphatic and subcutaneous filariasis (Wuchereria bancrofti, Brugia malayi, Loa loa, Onchocerca volvulus)", chapterId: "nematodes", synonyms: ["象皮病 elephantiasis","乳糜尿 chyluria","microfilaria periodicity","河川盲 river blindness","豹皮花紋 leopard skin","tropical pulmonary eosinophilia"] },
  { id: "angiostrongyliasis-and-larva-migrans", zh: "廣東住血線蟲症與幼蟲移行症（內臟／皮膚型）", en: "angiostrongyliasis and larva migrans syndromes (visceral / cutaneous)", chapterId: "nematodes", synonyms: ["嗜酸性腦膜炎 eosinophilic meningitis","廣東住血線蟲 Angiostrongylus cantonensis","犬蛔蟲 Toxocara canis","內臟幼蟲移行症 VLM","皮膚幼蟲移行症 CLM","犬鉤蟲 Ancylostoma caninum"], bottomUp: true },
  { id: "schistosomiasis", zh: "血吸蟲症（日本／埃及／曼氏血吸蟲）", en: "schistosomiasis (Schistosoma japonicum, S. haematobium, S. mansoni)", chapterId: "trematodes", synonyms: ["片山熱 Katayama fever","血尿 hematuria","膀胱癌 bladder cancer","尾刺蟲卵 terminal spine egg","雌雄異體 dioecious","肉芽腫 granuloma"] },
  { id: "paragonimiasis-and-ectopic-lesions", zh: "肺吸蟲症與吸蟲異位病變", en: "paragonimiasis and ectopic fluke lesions (Paragonimus westermani)", chapterId: "trematodes", synonyms: ["衛氏肺吸蟲","醉蟹 drunken crab","血痰 blood-tinged sputum","Charcot-Leyden crystals","咽喉型 halzoun","異位腦病變 ectopic CNS lesion"] },
  { id: "liver-and-intestinal-flukes", zh: "肝吸蟲與腸道吸蟲（中華肝吸蟲／異形吸蟲）", en: "liver and intestinal flukes (Clonorchis sinensis, Heterophyes heterophyes)", chapterId: "trematodes", synonyms: ["中華肝吸蟲症 clonorchiasis","異形吸蟲症","膽管癌 cholangiocarcinoma","囊幼 metacercaria","第三吸盤 third sucker"] },
  { id: "echinococcosis-and-small-tapeworms", zh: "包生絛蟲症與小型絛蟲（單胞／多胞絛蟲、短小／縮小包膜絛蟲、犬複殖器絛蟲）", en: "echinococcosis and small tapeworms (Echinococcus granulosus/multilocularis, Hymenolepis nana/diminuta, Dipylidium caninum)", chapterId: "cestodes", synonyms: ["包生囊 hydatid cyst","肺泡狀囊 alveolar cyst","短小包膜絛蟲自體感染","跳蚤中間宿主","絛蟲頭節 scolex"] },
  { id: "taeniasis-and-cysticercosis", zh: "條蟲病與囊尾幼蟲症（豬肉／牛肉絛蟲）", en: "taeniasis and cysticercosis (Taenia solium, Taenia saginata)", chapterId: "cestodes", synonyms: ["神經性囊尾幼蟲症 neurocysticercosis","豬囊尾幼蟲症 cysticercosis cellulosae","人為終宿主兼中間宿主"] },
  { id: "diphyllobothriasis-and-sparganosis", zh: "廣節裂頭絛蟲症與孔雀蚴／裂頭蚴移行症", en: "diphyllobothriasis and sparganosis (Diphyllobothrium latum, Spirometra mansonoides)", chapterId: "cestodes", synonyms: ["維他命B12缺乏","裂頭蚴 plerocercoid","原尾幼蟲 procercoid","卵蓋 operculum"] },
  { id: "malaria-plasmodium", zh: "瘧疾（瘧原蟲生活史、致病機轉與併發症）", en: "malaria (Plasmodium spp. life cycle, pathogenesis, and complications)", chapterId: "protozoa", synonyms: ["間日瘧 P. vivax","惡性瘧 P. falciparum","三日瘧 P. malariae","卵形瘧 P. ovale","諾氏瘧原蟲 P. knowlesi","黑水熱 blackwater fever","隱眠體 hypnozoite","細胞附著 cytoadherence"] },
  { id: "free-living-amoebae-and-flagellates", zh: "自由生活阿米巴與腸道／泌尿生殖道鞭毛蟲（含隱孢子蟲）", en: "free-living amoebae and flagellates (Naegleria fowleri, Acanthamoeba, Giardia lamblia, Trichomonas vaginalis, Cryptosporidium spp.)", chapterId: "protozoa", synonyms: ["原發性阿米巴腦膜腦炎 PAM","肉芽腫性阿米巴腦炎 GAE","棘阿米巴角膜炎","梨形鞭毛蟲症 giardiasis","陰道滴蟲症 trichomoniasis","隱孢子蟲症 cryptosporidiosis"], bottomUp: true },
  { id: "leishmaniasis", zh: "利什曼原蟲症（內臟型黑熱病與皮膚型）", en: "leishmaniasis (visceral kala-azar and cutaneous forms)", chapterId: "protozoa", synonyms: ["黑熱病 kala-azar","杜氏利什曼原蟲 L. donovani","無鞭毛體 amastigote","白蛉 sandfly","後黑熱病皮膚利什曼原蟲症"] },
  { id: "intestinal-luminal-amoebae", zh: "腸道管腔阿米巴（痢疾阿米巴及其他非致病性阿米巴）", en: "intestinal luminal amoebae (Entamoeba histolytica and non-pathogenic amoebae)", chapterId: "protozoa", synonyms: ["阿米巴痢疾 amebic dysentery","阿米巴肝膿瘍 amebic liver abscess","阿米巴腫 ameboma","大腸阿米巴 E. coli","哈氏阿米巴","嗜碘阿米巴"] },
  { id: "trypanosomiasis", zh: "錐蟲病（美洲卡格氏症與非洲昏睡病）", en: "trypanosomiasis (Chagas disease and African sleeping sickness)", chapterId: "protozoa", synonyms: ["卡格氏症 Chagas' disease","枯西氏錐蟲 T. cruzi","昏睡病 sleeping sickness","岡比亞錐蟲","羅得西亞錐蟲","采采蠅 tsetse fly","錐鼻蟲 kissing bug","Romaña's sign"] },
  { id: "babesiosis", zh: "巴貝氏原蟲病", en: "babesiosis (Babesia spp.)", chapterId: "protozoa", synonyms: ["雙核形 binucleate form","硬蜱 Ixodes","溶血性貧血","脾臟切除病人重症"] },
  { id: "toxoplasmosis", zh: "弓蟲症", en: "toxoplasmosis (Toxoplasma gondii)", chapterId: "protozoa", synonyms: ["弓形蟲","貓為終宿主","先天性弓蟲症","弓蟲腦炎 Toxoplasma encephalitis"] },
  { id: "scrub-typhus-chigger-mite", zh: "恙蟲病與恙蟎媒介", en: "scrub typhus (Orientia tsutsugamushi) and chigger mite vector", chapterId: "arthropod-vectors", synonyms: ["恙蟲病 scrub typhus / tsutsugamushi disease","地里恙蟎 Leptotrombidium deliense","Orientia tsutsugamushi","恙蟎 chigger mite"] },
  { id: "dust-mite-allergy", zh: "塵蟎過敏原與氣喘", en: "house dust mite allergen and asthma", chapterId: "arthropod-vectors", synonyms: ["塵蟎 dust mite","致敏原 allergen","house dust mite","兒童氣喘 asthma allergen"] },
  { id: "tick-borne-disease", zh: "蜱媒介疾病（萊姆病、艾利希體症、回歸熱等）", en: "tick-borne disease (Lyme disease, ehrlichiosis, relapsing fever, tick-borne rickettsioses)", chapterId: "arthropod-vectors", synonyms: ["萊姆病 Lyme disease","伯氏疏螺旋體 Borrelia burgdorferi","遊走性紅斑 erythema migrans","艾利克次體症 ehrlichiosis","回歸熱 relapsing fever","軟蜱 soft tick"] },
  { id: "louse-flea-mechanical-vectors", zh: "蝨蚤媒介疾病與機械性傳播（流行性斑疹傷寒、鼠疫、蠅蛆症）", en: "louse- and flea-borne disease and mechanical transmission (epidemic typhus, plague, myiasis)", chapterId: "arthropod-vectors", synonyms: ["流行性斑疹傷寒 epidemic typhus","體蝨 body louse","鼠疫 plague","鼠蚤 Xenopsylla cheopis","蠅蛆症 myiasis","機械性傳播 mechanical transmission","家蠅 house fly"] },
  ],
}
