export * from './types'
export { getDB, resetDB, StudyRpgDB } from './lib/db'
export type {
  LocalBackupRecord,
  MentorBacklogRecord,
  MockInProgressRecord,
} from './lib/db'
export {
  rollRarity,
  pickItemByRarity,
  rollLoot,
  instanceFromRoll,
  initialLootStats,
  randomId,
  DEFAULT_RARITY_WEIGHTS,
  PITY_SR_THRESHOLD,
  PITY_SSR_THRESHOLD,
  type RollResult,
} from './lib/loot'
export {
  rollGacha,
  initialGachaStats,
  type GachaTier,
  type PityRule,
  type GachaConfig,
  type GachaStats,
  type GachaRollResult,
} from './lib/gacha'
export {
  xpToNext,
  xpAtLevel,
  levelFromTotalXp,
  applyXp,
  addStat,
  newPlayer,
  REWARD,
  FAST_ANSWER_THRESHOLD_MS,
  MOCK_PASS_LOOT_GUARANTEED_TIER,
  type XpGainResult,
} from './lib/xp'
export {
  scoreMock,
  computeProgressDelta,
  applyMockPassReward,
  paperIdOf,
  decodePaperId,
  type MockSubmitInput,
  type MockScoreResult,
  type ProgressDelta,
  type MockPassRewardOutcome,
} from './lib/mock-exam'
export {
  pickDailyQuestion,
  enqueueBacklogForMissedDays,
  initialBacklog,
  consumeBacklog,
  computeMentorReward,
  mentorToday,
  MENTOR_BACKLOG_CAP,
  MENTOR_LOOKBACK_DAYS,
  type MentorPickInput,
  type MentorPickResult,
  type MentorPickMode,
  type MentorRewardOutcome,
} from './lib/mentor-daily'
export {
  cosmeticSlotForCategory,
  cosmeticToItem,
  checkMilestoneUnlocks,
  equipCosmetic,
  unequipCosmetic,
  instanceFromCosmetic,
  listUnlockedCosmetics,
  listLockedCosmetics,
} from './lib/cosmetic'
export {
  STREAK_CHECK_IN_THRESHOLD,
  STREAK_MULTIPLIER_CAP_DAYS,
  getTaipeiToday,
  getTaipeiYesterday,
  getStreakMultiplier,
  applyCheckIn,
  ensureTodayProgress,
  incrementReadingMinutes,
  incrementQuestionsAnswered,
  hasMetCheckInThreshold,
} from './lib/streak'
export {
  newCard,
  reviewCard,
  reviewCardBinary,
  dueCards,
  WRONG_INTERVAL_MULTIPLIER,
  WRONG_EASE_MULTIPLIER,
  STANDARD_INITIAL_INTERVALS,
  SRS_DAILY_CAP,
  MAX_INTERVAL_DAYS,
  type BinaryReviewInput,
  type BinaryReviewPrev,
  type BinaryReviewResult,
} from './lib/srs'
export { quizEvents, type QuizEventName } from './lib/quizEvents'
export {
  sampleMiniBoss,
  passed,
  badgeId,
  BOSS_PASS_THRESHOLD,
  MINI_BOSS_QUESTIONS,
  MINI_BOSS_UNLOCK_SUBJECT_XP,
  MINI_BOSS_DURATION_MS,
  ANNUAL_BOSS_DURATION_MS,
} from './lib/boss'
export {
  unlockedCount,
  detectUnlocks,
  resolveSkillTree,
  thresholdForIndex,
  ENGINE_FALLBACK_SKILL_TREE,
  SKILL_BRANCH_ORDER,
  SKILL_TREE_NODES_PER_BRANCH,
  SKILL_TREE_THRESHOLD_STEP,
  type SkillNode,
  type SkillBranch,
  type SkillBranchStatKey,
  type SkillTreeContent,
} from './lib/skillTree'
export {
  selectUnderUtilizedSubject,
  pickERConsultQuestion,
  shouldRollERConsult,
  computeERConsultReward,
  jitterTicksUntilNextERConsult,
  ER_CONSULT_REWARD_MULTIPLIER,
  ER_CONSULT_TICK_INTERVAL_MIN,
  ER_CONSULT_TICK_INTERVAL_MAX,
  ER_CONSULT_LOG_CAP,
  ER_CONSULT_RECENT_ANSWER_WINDOW_MS,
  ER_CONSULT_RECENCY_WINDOW_MS,
  ER_CONSULT_SUBJECT_COOLDOWN_THRESHOLD,
  ER_CONSULT_SUBJECT_COOLDOWN_MULTIPLIER,
  ER_CONSULT_AUTO_SKIP_MS,
  type ERConsultSelectorInput,
  type ERConsultQuestionPickerInput,
  type ERConsultMutexState,
  type MasteryCounter as ERConsultMasteryCounter,
} from './lib/er-consultation'
export {
  BUG_REPORT_CATEGORIES,
  BUG_REPORT_SEVERITIES,
  BUG_REPORT_REPRODUCIBILITY,
  BUG_REPORT_APPS,
  QUIZ_BUG_TARGETS,
  QUIZ_BUG_TARGET_TO_CATEGORY,
  type BugReportCategory,
  type BugReportSeverity,
  type BugReportReproducibility,
  type BugReportApp,
  type QuizBugTarget,
  type ConsoleErrorEntry,
  type BugReportUserFields,
  type BugReportAutoContext,
  type BugReportRow,
  type SyncDiagnosticSnapshot,
} from './lib/bug-report-types'
